### ISSUE TITLE
AttributeError: 'MultiIndex' object has no attribute 'labels'

### ISSUE THREAD

**Issue by jan-kwiatkowski** [ktrueda/parquet-tools#14]
I tried installing with few python versions including 3.8 and  3.6 and both installed successfully, however executing `parquet-tools`
returns error as in title.

**Comment by ktrueda** [comment]
@jan-kwiatkowski Thank you for making issue.

I couldn't reproduce your problem in my machine. 
Please give me some information about 
- command you run
- traceback
- parquet file

**Comment by jan-kwiatkowski** [comment]
I tried again with python 3.6 and it worked sorry for inconvenience.

**Comment by jan-kwiatkowski** [comment]
Ahhh i was to fast with my decision...

`parquet-tools show --head 10 part-00000-4e3db85b-c311-4e96-80c9-15ec0982db20-c000.snappy.parquet 
Traceback (most recent call last):
  File "/home/jan-k/.local/bin/parquet-tools", line 8, in <module>
    sys.exit(main())
  File "/home/jan-k/.local/lib/python3.6/site-packages/parquet_tools/cli.py", line 26, in main
    args.handler(args)
  File "/home/jan-k/.local/lib/python3.6/site-packages/parquet_tools/commands/show.py", line 60, in _cli
    with get_datafame_from_objs(pfs, args.head) as df:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/jan-k/.local/lib/python3.6/site-packages/parquet_tools/commands/utils.py", line 190, in get_datafame_from_objs
    df: Optional[pd.DataFrame] = stack.enter_context(pf.get_dataframe())
  File "/usr/lib/python3.6/contextlib.py", line 330, in enter_context
    result = _cm_type.__enter__(cm)
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/jan-k/.local/lib/python3.6/site-packages/parquet_tools/commands/utils.py", line 71, in get_dataframe
    yield pq.read_table(local_path).to_pandas()
  File "table.pxi", line 1120, in pyarrow.lib.Table.to_pandas
  File "/home/jan-k/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 612, in table_to_blockmanager
    columns = _flatten_single_level_multiindex(columns)
  File "/home/jan-k/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 742, in _flatten_single_level_multiindex
    labels, = index.labels
AttributeError: 'MultiIndex' object has no attribute 'labels'
`
