### ISSUE TITLE
Missing `dataclasses` in requirements

### ISSUE THREAD

**Issue by Tazoeur** [ktrueda/parquet-tools#24]
I just launched the installation of this package with pip `python3 -m pip install parquet-tools` on a debian server and got this error:
```
Traceback (most recent call last):
  File "/home/taz/.local/bin/parquet-tools", line 5, in <module>
    from parquet_tools.cli import main
  File "/home/taz/.local/lib/python3.6/site-packages/parquet_tools/cli.py", line 2, in <module>
    from parquet_tools.commands import show, csv, inspect
  File "/home/taz/.local/lib/python3.6/site-packages/parquet_tools/commands/show.py", line 9, in <module>
    from .utils import (FileNotFoundException, InvalidCommandExcpetion,
  File "/home/taz/.local/lib/python3.6/site-packages/parquet_tools/commands/utils.py", line 4, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

I can see that the `dataclasses` library is used in `parquet_tools/commands/utils.py` but not provided as dependency in `pyproject.toml`

**Comment by ktrueda** [comment]
Never mind. Thank you for making issue.
