### ISSUE TITLE
 File "/usr/lib/python2.7/site-packages/parquet_tools/cli.py", line 5

### ISSUE THREAD

**Issue by stevenlii** [ktrueda/parquet-tools#27]
```
Traceback (most recent call last):
  File "/usr/bin/parquet-tools", line 5, in <module>
    from parquet_tools.cli import main
  File "/usr/lib/python2.7/site-packages/parquet_tools/cli.py", line 5
    def main() -> None:
               ^
SyntaxError: invalid syntax

```

**Comment by ktrueda** [comment]
use Python >=3.8 .
