### ISSUE TITLE
Broken pipe when piping to `less`

### ISSUE THREAD

**Issue by maleasy** [ktrueda/parquet-tools#29]
When piping `parquet-tools csv` output to `less`, I consistently get a BrokenPipeError when `less` is closed:

```
> parquet-tools csv my.parquet | less
Traceback (most recent call last):
  File "/.../bin/parquet-tools", line 10, in <module>
    sys.exit(main())
  File ".../lib/python3.9/site-packages/parquet_tools/cli.py", line 26, in main
    args.handler(args)
  File "/.../lib/python3.9/site-packages/parquet_tools/commands/csv.py", line 46, in _cli
    _execute(
  File "/.../lib/python3.9/site-packages/parquet_tools/commands/csv.py", line 62, in _execute
    print(df_select.to_csv(index=None))
  File "/.../lib/python3.9/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/.../lib/python3.9/site-packages/colorama/ansitowin32.py", line 170, in write
    self.write_and_convert(text)
  File "/.../lib/python3.9/site-packages/colorama/ansitowin32.py", line 198, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/.../lib/python3.9/site-packages/colorama/ansitowin32.py", line 203, in write_plain_text
    self.wrapped.write(text[start:end])
BrokenPipeError: [Errno 32] Broken pipe
```

It is not a deal breaker, since in `less` I can see the output just fine. It is just a bit distracting, so I thought I'd mention it.

**Comment by fotonick** [comment]
This is common to all of Python. Ref: https://docs.python.org/3/library/signal.html#note-on-sigpipe

The recommended fix is:

```python
    try:
        # body of main()
    except BrokenPipeError:
        # Python flushes standard streams on exit; redirect remaining output
        # to devnull to avoid another BrokenPipeError at shutdown
        devnull = os.open(os.devnull, os.O_WRONLY)
        os.dup2(devnull, sys.stdout.fileno())
        sys.exit(1)  # Python exits with error code 1 on EPIPE
```
